[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224

[FILTER]
    Name          modify
    Match         *
    Add           source docker-container

[OUTPUT]
    Name          loki
    Match         *
    Host          loki
    Port          3100
    Labels        job=container-logs,source=fluent-bit
    Auto_Kubernetes_Labels off
    Line_Format   json