[SERVICE]
    Flush 1
    Daemon Off
    Log_Level info

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224

[FILTER]
    Name modify
    Match *
    Add service app

[OUTPUT]
    Name loki
    Match *
    Host loki
    Port 3100
    Labels job=container-logs,service=app
    Line_Format json
