#!/bin/bash
set -euo pipefail

echo "=== Starting Container Observability Stack ==="
echo "This will start: Elixir app + OTel Collector + Jaeger + Prometheus + Loki + Grafana + Fluent Bit"
echo ""

# Start all services
docker compose up -d --build

echo "Waiting for services to initialise..."
sleep 15

# Wait for app
echo -n "Waiting for app..."
until curl -sf http://localhost:4000/health > /dev/null 2>&1; do
    echo -n "."
    sleep 2
done
echo " ready!"

echo ""
echo "=== Stack is up! ==="
echo ""
echo "📊 Grafana:    http://localhost:3000   (anonymous admin access)"
echo "🔍 Jaeger:     http://localhost:16686  (distributed tracing)"
echo "📈 Prometheus: http://localhost:9090   (metrics)"
echo "📱 App:        http://localhost:4000   (Elixir Phoenix API)"
echo ""
echo "Generating sample load for dashboards..."
for i in $(seq 1 30); do
    curl -sf http://localhost:4000/items > /dev/null
    curl -sf http://localhost:4000/health > /dev/null
    curl -sf -X POST http://localhost:4000/items \
        -H "Content-Type: application/json" \
        -d "{\"name\": \"Item $i\", \"description\": \"Generated by load script\"}" > /dev/null
    sleep 0.5
done

echo ""
echo "Load generation complete! Check Grafana for traces and metrics."
echo "The dashboard is provisioned automatically from grafana/dashboards/app-dashboard.json"