apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talk-12-api
  namespace: container-series
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - talk-12.example.com
      secretName: talk-12-tls
  rules:
    - host: talk-12.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: talk-12-api
                port:
                  number: 8080
