apiVersion: v1
kind: Secret
metadata:
  name: talk-12-secrets
  namespace: container-series
type: Opaque
data:
  DATABASE_USERNAME: Y2hhbmdlbWU=
  DATABASE_PASSWORD: Y2hhbmdlbWU=
  API_KEY: Y2hhbmdlbWU=
