apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "container-series-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-series-app.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  APP_VERSION: {{ .Values.config.appVersion | quote }}
